# Generated by Django 3.0.7 on 2021-06-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votedby',
            name='polledOpt',
            field=models.IntegerField(default=-1),
        ),
    ]
