# Generated by Django 3.0.7 on 2021-06-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210611_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentby',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
